### ISSUE TITLE
[ENH] Mejora de la documentacion de codigo en general

### ISSUE THREAD

**Issue by dylanforit** [AgoraUS-G2-1617/G27-Sept#10]
Es necesaria una mejor documentacion de los metodos usados, ya que estos estan escritos de forma compleja y toma un tiempo entender lo que hace cada uno. Por tanto proponemos mejorar toda documentacion existente en cada metodo y crear una documentacion para aquellos que no tienen

**Comment by andgagon** [comment]
Se comentan los metodos de authorityimpl en commit: c5970219e6a6faeda1665fa441c4f1f12f2c4695

**Comment by andgagon** [comment]
Se añaden comentarios aclaratorios sobre metodos complejos: e88b562b90c73157a6aaba6f00a953f5e3729d0c

**Comment by andgagon** [comment]
Nuevos comentarios aclarativos: e503ad5
