### ISSUE TITLE
[BUG]  Error en la excepcion “VerificationException”. No es serializable 

### ISSUE THREAD

**Issue by albcasmol** [AgoraUS-G2-1617/G27-Sept#11]
Existe un pequeño error en la excepción creada, ya que esta no es serializable.
Basta con tratar de generar un token invalido y la excepción no será lanzada correctamente y obtendremos en cambio un “NotSerializableException”

**Comment by andgagon** [comment]
Error corregido, la excepcion es ahora serializable y queda corregido en commit: 83df022

**Comment by andgagon** [comment]
Cerramos issue, bug arreglado
