### ISSUE TITLE
[BUG] Error en el testeo de la nueva lista auxiliar de tokens

### ISSUE THREAD

**Issue by dylanforit** [AgoraUS-G2-1617/G27-Sept#13]
Se detecta un error en el testeo del nuevo metodo añadido en Issue #3. Es posible que se de un indexOutOfBoundException.

**Comment by albcasmol** [comment]
Se ha arreglado el bug y se procede a su merge con la rama develop en commit: c7163e934bcf6eadaae8417a6684b851a0983a58
