### ISSUE TITLE
Es necesario cambiar la BD a localhost para realizar las pruebas pertinentes

### ISSUE THREAD

**Issue by dylanforit** [AgoraUS-G2-1617/G27-Sept#14]
La base de datos que usaba el grupo de la iteracion anterior no se encuentra disponible, por tanto pasamos a cambiar la BD usada

**Comment by andgagon** [comment]
Las credenciales de la base de datos ha sido cambiada a una forma local en commit: 67213a52baa5d00aae58cb555bdced8d7ee6558f
