### ISSUE TITLE
[ENH] Refactorización Test

### ISSUE THREAD

**Issue by Hug0Ramos** [AgoraUS-G2-1617/G27-Sept#25]
Es necesaria la refactorización de la batería de los test para los nuevos tokens.

**Comment by andgagon** [comment]
Los tests han sido refactorizados para comprobar la consistencia de los nuevos tokens y sus checks en commit: 755602d47f1a7bfdbad9647c6be21d3c2f407848

**Comment by andgagon** [comment]
Se añade test de borrado de tokens por parte de Hugo:  4e5e3f3
