### ISSUE TITLE
[ENH] Modificacion del método calculateToken

### ISSUE THREAD

**Issue by andgagon** [AgoraUS-G2-1617/G27-Sept#5]
Debido a los cambios anteriores, es necesario rehacer la forma en la que se generan los tokens a partir de los votos

**Comment by albcasmol** [comment]
El metodo calculateToken ahora acepta el nuevo tipo de tokens. 
Commit: eaf1d18

**Comment by andgagon** [comment]
Se refactoriza el metodo ya que estaba dando errores a la hora de testear en commit: 2da78fd
