### ISSUE TITLE
[ENH] Cambio de MD5 hash a binario

### ISSUE THREAD

**Issue by albcasmol** [AgoraUS-G2-1617/G27-Sept#54]
Se ha decidido realizar esta mejora para la defensa de septiembre. La mejora consiste en cambiar la codificación MD5 hash a binario para comprobar que el encriptado/desencriptado funciona correctamente

**Comment by andgagon** [comment]
Se sube rama con cambio de generacion de tokens a feature/cambioDefensa a falta del test en commit 4949a7b50dadb74dad303428bf1faa93fc57e0dc

**Comment by andgagon** [comment]
Cierro con el test comiteado
