### ISSUE TITLE
[ENH] Creación y mejora de .gitignore

### ISSUE THREAD

**Issue by Hug0Ramos** [AgoraUS-G2-1617/G27-Sept#9]
Es necesario que se cambie el .gitignore del proyecto para que no se suban archivos no deseados.

**Comment by albcasmol** [comment]
Se realiza una primera version del .gitignore en commit: 24ac0ac254a8bea13bd415a03b8afc5aad607359

**Comment by albcasmol** [comment]
Se mejora el gitignore de forma necesaria en commit: 1e98a64ad724f25944ee571b7b03773723f38897
